name: Metrics
on:

  # Schedule every day updates
  schedule: 
    - cron: "0 0 * * *"

  # allow run workflow manually
  workflow_dispatch:

jobs:

  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:

      - name: 👤 General
        uses: lowlighter/metrics@latest
        with:
          filename: metrics/general.svg
          config_display: large
          token: ${{ secrets.METRICS_TOKEN }}

      - name: 🧱 Isometric Calendar 
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: metrics/isocalendar.svg
          config_display: regular
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          token: ${{ secrets.METRICS_TOKEN }}
      
      - name: 📚 Topics
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: metrics/topics.svg
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: icons
          token: ${{ secrets.METRICS_TOKEN }}
      
      - name: 📙 Languages
        uses: lowlighter/metrics@latest
        with:
          base: ""
          filename: metrics/languages.svg
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_recent_load: 400
          plugin_languages_recent_days: 14
          token: ${{ secrets.METRICS_TOKEN }}

  snake:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:

      - name: 🐍 Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg?color_snake=#ec4899&color_dots=#e0e7ff,#a5b4fc,#6366f1,#4338ca,#312e81
            dist/github-snake-dark.svg?color_snake=#ec4899&color_dots=#1e293b,#312e81,#4338ca,#6366f1,#a5b4fc

      - uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: snake
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
